// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnmssqvs5iWB9rnsN8BWw5teOROpI6pHI',
    appId: '1:54479790914:web:636a8ee2d48fed7c919edb',
    messagingSenderId: '54479790914',
    projectId: 'fyp-language',
    authDomain: 'fyp-language.firebaseapp.com',
    storageBucket: 'fyp-language.appspot.com',
    measurementId: 'G-KJG7EVL0EL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2DHtHpofRQuH3bGDOLuHArV51vB_NWBY',
    appId: '1:54479790914:android:a3086fdc6e06b7e4919edb',
    messagingSenderId: '54479790914',
    projectId: 'fyp-language',
    storageBucket: 'fyp-language.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaEI3C86ZRJ2Ysk36ZdN5-gDUTOg47F70',
    appId: '1:54479790914:ios:ec9b6d03f7173db7919edb',
    messagingSenderId: '54479790914',
    projectId: 'fyp-language',
    storageBucket: 'fyp-language.appspot.com',
    iosBundleId: 'com.example.fypLanguage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaEI3C86ZRJ2Ysk36ZdN5-gDUTOg47F70',
    appId: '1:54479790914:ios:ec9b6d03f7173db7919edb',
    messagingSenderId: '54479790914',
    projectId: 'fyp-language',
    storageBucket: 'fyp-language.appspot.com',
    iosBundleId: 'com.example.fypLanguage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnmssqvs5iWB9rnsN8BWw5teOROpI6pHI',
    appId: '1:54479790914:web:2269bb738a152ea7919edb',
    messagingSenderId: '54479790914',
    projectId: 'fyp-language',
    authDomain: 'fyp-language.firebaseapp.com',
    storageBucket: 'fyp-language.appspot.com',
    measurementId: 'G-9WMKJ59F2F',
  );
}
